services:
  backend:
    # container_name: Back
    image: image-search
    ports:
      - '8080:80'
    volumes:
      - ./data:/app/data
  
  frontend:
    # container_name: Front
    image: image-search-front
    ports:
      - '8000:8000'
    environment:
      - APP_PORT = 8000
  
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prod_db
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:rw"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
